# Generated by Django 4.2.7 on 2023-11-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rareusers',
            old_name='user_id',
            new_name='user',
        ),
    ]
